//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOicom
{
    using System;
    using System.Collections.Generic;
    
    public partial class maquinas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public maquinas()
        {
            this.mediciones = new HashSet<mediciones>();
            this.medicionesfiltros = new HashSet<medicionesfiltros>();
            this.reportes = new HashSet<reportes>();
        }
    
        public string noserie { get; set; }
        public Nullable<int> noeconomico { get; set; }
        public string marca { get; set; }
        public Nullable<int> modelo { get; set; }
        public Nullable<int> aniofabricacion { get; set; }
        public Nullable<int> idequipo { get; set; }
        public string imagen { get; set; }
    
        public virtual equipoauxiliar equipoauxiliar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mediciones> mediciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medicionesfiltros> medicionesfiltros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reportes> reportes { get; set; }
    }
}
