//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOicom
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reportes()
        {
            this.refacciones_reporte = new HashSet<refacciones_reporte>();
        }
    
        public int folio { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string no_serie { get; set; }
        public Nullable<decimal> km_horometro { get; set; }
        public Nullable<int> modelo { get; set; }
        public Nullable<int> idreporto { get; set; }
        public Nullable<int> idtipofalla { get; set; }
        public Nullable<int> idatiende { get; set; }
        public Nullable<int> idrealizo { get; set; }
        public Nullable<int> tiempo_reparacion { get; set; }
        public Nullable<byte> retraso { get; set; }
        public Nullable<int> idtipomto { get; set; }
        public string descripcion { get; set; }
        public string observaciones { get; set; }
    
        public virtual maquinas maquinas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<refacciones_reporte> refacciones_reporte { get; set; }
        public virtual tipofallas tipofallas { get; set; }
        public virtual tipomantenimientos tipomantenimientos { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual usuarios usuarios1 { get; set; }
        public virtual usuarios usuarios2 { get; set; }
    }
}
