//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOicom
{
    using System;
    using System.Collections.Generic;
    
    public partial class requerimientos_solicitudes
    {
        public int norequerimiento { get; set; }
        public int foliosolicitud { get; set; }
        public string equipo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
    
        public virtual solicitudmaquinaria solicitudmaquinaria { get; set; }
    }
}
