//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOicom
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudmaquinaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public solicitudmaquinaria()
        {
            this.requerimientos_solicitudes = new HashSet<requerimientos_solicitudes>();
        }
    
        public int folio { get; set; }
        public Nullable<int> idobra { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<System.DateTime> requeridopara { get; set; }
        public Nullable<int> idresponsable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requerimientos_solicitudes> requerimientos_solicitudes { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual obras obras { get; set; }
    }
}
