//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOicom
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareasPlanificador
    {
        public long idtarea { get; set; }
        public Nullable<long> idcategoria { get; set; }
        public string titulo { get; set; }
        public Nullable<byte> todoDia { get; set; }
        public Nullable<System.DateTime> fechainicio { get; set; }
        public Nullable<System.TimeSpan> horainicio { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
        public Nullable<System.TimeSpan> horafin { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
        public Nullable<decimal> horas { get; set; }
        public string notas { get; set; }
    
        public virtual categoriasPlanificador categoriasPlanificador { get; set; }
    }
}
