//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOicom
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.reportes = new HashSet<reportes>();
            this.reportes1 = new HashSet<reportes>();
            this.reportes2 = new HashSet<reportes>();
            this.eventosagenda = new HashSet<eventosagenda>();
            this.chat_eventos = new HashSet<chat_eventos>();
            this.categoriasPlanificador = new HashSet<categoriasPlanificador>();
            this.chat_general = new HashSet<chat_general>();
            this.solicitudmaquinaria = new HashSet<solicitudmaquinaria>();
            this.solicitudmaquinaria1 = new HashSet<solicitudmaquinaria>();
        }
    
        public int idusuario { get; set; }
        public string nombre { get; set; }
        public string apepaterno { get; set; }
        public string apematerno { get; set; }
        public string telefono { get; set; }
        public string mail { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<int> idpuesto { get; set; }
        public string passapp { get; set; }
        public string usuario { get; set; }
    
        public virtual puestos puestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reportes> reportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reportes> reportes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reportes> reportes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventosagenda> eventosagenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chat_eventos> chat_eventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<categoriasPlanificador> categoriasPlanificador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chat_general> chat_general { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solicitudmaquinaria> solicitudmaquinaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solicitudmaquinaria> solicitudmaquinaria1 { get; set; }
    }
}
